name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://${{secrets.GH_PAT}}@github.com/shubham21155102/DevOps.git
          cd DevOps

      - name: Update diagram
        run: |
          cd DevOps
          npx githubocto/repo-visualizer --token ${{ secrets.GITHUB_TOKEN }} --username ${{ github.repository_owner }} --excluded-paths "ignore,.github"

      - name: Commit changes
        run: |
          cd DevOps
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add diagram.svg
          git commit -m "Repo visualizer: update diagram"

      - name: Push changes
        run: |
          cd DevOps
          git push https://${{secrets.GH_PAT}}@github.com/shubham21155102/DevOps.git HEAD:main