name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://${{secrets.GH_PAT}}@github.com/shubham21155102/DevOps.git
          cd DevOps

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          excluded_paths: "ignore,.github"

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add diagram.svg
          git commit -m "Repo visualizer: update diagram"

      - name: Push changes
        run: |
          git push https://${{secrets.GH_PAT}}@github.com/shubham21155102/DevOps.git HEAD:main