name: SSH into EC2 Instance

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #   - name: Upgrade System
    #     run: |
    #       sudo apt-get update
    #       sudo apt-get upgrade -y

      - name: Setup SSH and Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Write SSH Key to File
        run: echo "${{ secrets.ACENCORE_PEM_KEY }}" > acencore.pem

      - name: Restrict Permissions of SSH Key
        run: chmod 400 acencore.pem

      - name: Debugging Output List Files
        run: |
          ls -a
          ls -l

      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.ACENCORE_PEM_KEY }}
    #   - name: SSH into EC2 Instance and Execute Command
    #     run: |
    #       ssh -o StrictHostKeyChecking=no -i acencore.pem "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}" "sudo rm -rf acencore-ml"
      - name: SSH into EC2 Instance and Execute Command
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.ACENCORE_PEM_KEY }}") "${{ secrets.EC2_USER }}"@"${{ secrets.EC2_HOST }}" "sudo rm -rf acencore-ml"
  