name: SSH in TO EC2
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        #    - name: Upgrade System
        #      run: sudo apt-get update && sudo apt upgrade
           - name: Get PEM Key
             run: echo "${{secrets.ACENCORE_PEM_KEY}}"
           - name: Write PEM key
             run: echo "${{secrets.ACENCORE_PEM_KEY}}" >> acencore.pem